import java.util.ArrayList;

/**
 * @author 33674
 * @version 1.0
 */

public class Deck {
	
	/**
	 * @see Cards
	 */
	
	static ArrayList<Cards> deck;

	public Deck() {
		
		// TODO Auto-generated constructor stub
	}
	
	/**
	 * 
	 * @param deck1
	 */
	public Deck(ArrayList<Cards> deck1) {
		
		Deck.deck = new ArrayList<Cards>();
	}
	
	public static void AddCardDeck() {
		
		Cards fool = new Cards("The Fool", "The Fool is a very powerful card in the Tarot deck, usually representing a new beginning -- and, consequently, an end to something in your old life. The Fool's position in your spread reveals which aspects of your life may be subject to change. The Fool portends important decisions ahead which may not be easy to make, and involve an element of risk for you. Approach the changes with optimism and care to gain the most positive outcome.", "The risks you have taken and your original thinking have brought you success. By doing things in a new way, you have allowed for great potential.", "At this moment, you are entering a new phase of life. The experience of this change may seem good or bad now, but its influence will be clearer in the future. Assessing the risks is crucial to making the right choice.", "In order to succeed, you must find new ways to bring about the achievement of your goals. When the opportunity comes, you must be willing to shed old habits and if it never comes, it may be time to create it for yourself with new methods.", "https://www.trustedtarot.com/img/cards/the-fool.png");
		Cards magician = new Cards("The Magician", "The Magician generally associates with intelligent and skillful communicators. His presence in your spread indicates a level of self-confidence and drive which allows you to translate ideas into action. A practical card, the revelations it brings are best applied to the pragmatic and physical aspects of your life, rather then the ephemeral or theoretical. Your success in upcoming ventures in politics or business will likely hinge upon your own strength of will and determination.", "Your confidence and creativity have allowed you to effectively make your ideas into reality. You have found success through intelligence and skillful execution.", "Presently, there is a need for your knowledge and skills to influence the changes that are occuring. In order to make the changes beneficial, you must play your cards right.", "The future before you is uncertain, presenting both risk and opportunity. The possibilities will be influenced by the friendships you have nurtured and the support you have from those who are close. A triumph or creative success may bring about a new beginning for you.", "https://www.trustedtarot.com/img/cards/the-magician.png");
		Cards priestess = new Cards("The High Priestess", "Your identification with the High Priestess suggests you possess inherent good judgment, in the form of strong intuition. She may indicate that reason should take second place to instinct. Your head must trust in the wisdom of your heart for a change. Yet, she is also an aide by nature, and her presence in certain parts of your spread could be indicative of someone close to you coming to your rescue with their own intuition. Intuition is most effective at seeing what is hidden to the senses, so the High Priestess may also come as a warning of concealed facts or influences that are, or will be, important to you.","You have been in need of new experiences and may wander somewhere outside of your comfort zone. If you are lacking support in important areas of your life, you should consider the idea of investing your time in new people and new ideas. You are entering a time of renewal, but you may need the help of another.","The undiscovered or repressed creative abilities you have are demanding to be expressed. Finding a spiritual guide will help you realize the full potential of your psychic or artistic abilities. In order to get what you desire, you will need to overcome your fear of commitment.", "You are on course to receive real rewards, but only if you continue your discipline and motivation. If you reject the attempts to dissuade you, your future is bright. Follow your intuition and you are headed towards the lasting contentment of success.", "https://www.trustedtarot.com/img/cards/the-high-priestess.png");
		Cards empress = new Cards("The Empress", "Traditionally associated with strong maternal influence, the presence of the Empress is excellent news if you are looking for harmony in your marriage or hoping to start a family. Any artistic endeavours you are currently associated with are also likely to be more successful, as this card often finds those exposed to strong bursts of creative or artistic energy. That creative energy may not be in the form of a painting or art project, however: This card also suggests a very strong possibility of pregnancy -- not necessarily yours, but you might be seeing a new addition to your extended family or the family of a close friend in the near future! This card is a good portent for you and those around you.","The last opportunity you had is proving its influence now. Whether business, personal, or artistic, a new partnership will require your continued effort to succeed. Remember your most resourceful behaviors, but especially your discipline.","There may be a new beginning unfolding before you and you decided its quality. Be understanding and especially sensitive to the emotional aspects of life. A loved one will need a helping hand or light in the dark. The role is yours to fill, no matter your choice.", "The future will bring healing and respite for your emotional and physical wounds. Spending time walking on new paths will be more beneficial than mending bridges. Your investments will pay off if you carefully tend them.", "https://www.trustedtarot.com/img/cards/the-empress.png");
		Cards emperor = new Cards("The Emperor", "Counterpart to the Empress, the Emperor is signifies a powerful influence, generally male in nature. This can also include concepts in your life historically considered masculine, such as leadership and authority, self-discipline, and stability through the power of action. Its positive influences suggest you may be on a path to advancement or promotion, but it can also be neutral. Often a companion to those destined to take on greater responsibility, it may presage change or loss that necessitates you stepping forward to shoulder a greater burden than you have in the past. Whatever the impetus for the change, it indicates you may possess an uncommon inner strength that will compel you act and to lead.", "Authority has played a great role in shaping your life. Your good position may be due to a government or a powerful person. The resolution of a recent conflict is approaching.", "There may be a moment where someone in a position of authority offers to help you. In any form, the more experienced hand that has come to help you may be more capable than yours. Protecting your loved ones is important, but those in a leadership position must know how to compromise. Beware the overly-dependant.", "Taking the initiative may lead you closer to your goal, but only if you can bear the responsibility of all your actions. You will be given the opportunity to lead in one of life's many roles. Remember those who follow behind you.", "https://www.trustedtarot.com/img/cards/the-emperor.png");
		Cards hierophant = new Cards("The Hierophant", "Depending on your own nature, the Hierophant can mean very different things. At its root, it represents doctrine, but doctrine can come in the form of teaching and guidance or rigid authority. Where it appears in your spread is also important, as it is most often indicative of your own approach to the moral, religious, and social conventions of the world. Considered wisely, it helps show the path towards fulfillment.", "There is value in an ambition from your past. Look to a strength that you may have neglected.", "The opportunity for work or study under a superior is approaching. If the others around you are capable of being wrong, so are you.", "Look to the support of a solid organization or structured principles to achieve success. Your actions should be motivated beyond selfish reasons, or there will be little reward for them.", "https://www.trustedtarot.com/img/cards/the-heirophant.png");
		Cards lovers = new Cards("The Lovers", "Your first instinct will most likely be to associate this card as representing love, but, much like love, it does not possess a simple nature. Not only does love comes in many forms, but the Lovers may indicate important or difficult choices ahead in your life. This is bad, in that the choices it portends are generally mutually exclusive, paths to two very different futures, but also good, in that it also confirms that at least one of those paths will take you to a good place. As such, if you happen to find it in your spread, you should consider it carefully, but not fear it. It tells a story of difficult choices, likely painful, but that the correct decision and a positive outcome are within your grasp.", "By becoming more in tune with yourself, you will be more able to connect with others. The emotional burden of a recent conflict will soon be lifted and a successful resolution reached.", "There is an approaching conflict that will test your values. In order to progress, you are going to have to make a decision between love and career. Neither will disappear forever, but the choice will shape your priorities.", "It will benefit you to remember that opposites are two sides of the same coin; there is not one without the other. The right choice will be made only if you have accepted others and yourself.", "https://www.trustedtarot.com/img/cards/the-lovers.png");
		Cards chariot = new Cards("The Chariot", "You have some hard work ahead of you. It may be resolved quickly, but the Chariot is a powerful card, and the labor you are undertaking will probably trend towards long and difficult. You will quite possibly experience rough roads, long uphill slopes, dead ends, and painful setbacks. A good outcome is only assured if the card is upright, but do not let yourself lose hope: This hard road will instil in you a strength of purpose, the ability to overcome through organization and endurance, and the confidence possessed only by those who have done what they thought they could not. Harnessed correctly, few forces can stand against an individual like that.", "Your character has been tested by the tendency to protect your own interests and ego. The struggle has strengthened you and recent events have given you a chance to accomplish your victory.", "Good news is coming and you will better the opposition in a decisive victory.", "Continue your struggle and the end you seek will be achieved. Honor, acclaim, and recognition are all possible outcomes for you if you do not quit.", "https://www.trustedtarot.com/img/cards/the-chariot.png");
		Cards strength = new Cards("Strength", "Strength is the rawest form of power, and you possess it in some form. It is a very happy card if you are fighting illness or recovering from injury. As might be suspected, its influence over you, and the use you put it to, can trend towards light or dark. You likely trend towards facing your problems courageously, head-on, and conquering them through perseverance and will. With this ability to overcome life's obstacles, though, comes the responsibility to control yourself, and it this card may be a warning to take command of your own actions or emotions before they damage you or the people you care about.", "Your strength is balanced and you have both physical endurance and mental strength. This inner strength may lead you to explore the other potentials for your abilities.", "Do not turn down any offers that will change your future. Have faith in your own convictions, and be strong enough to trust where you will land.", "There is a strong, energetic release in your future which will lead you into major life changes. By understanding your true value, you will make the most of a wonderful chance to improve your life.", "https://www.trustedtarot.com/img/cards/strength.png");
		Cards hermit = new Cards("The Hermit", "There are times in every life, when one must step back and make a careful examination of their situations and decisions. Finding the Hermit in your spread suggests this is just such a time for you. You are in need of a period of inner reflection, away from the current demands of your position. This retreat can be physical, or a search within. Only a deep and honest introspection will lead to a solution, however.", "The pace of your past has slowed, and it is time to accept this. Continue looking for your finals goals and consider the insight you have recently gained.", "There is someone who can help you through all your problems, and their insight may surprise you. This person is yourself. By understanding yourself, you can better understand others.", "When you become aware of your true road, there will be nothing to stand in your way. Life has challenged you, but you are prepared to make the best of the future.", "https://www.trustedtarot.com/img/cards/the-hermit.png");
		Cards wheel = new Cards("The Wheel of Fortune", "Symbolic of life's cycles, the Wheel of Fortune speaks to good beginnings. Most likely, you will find the events foretold to be positive, but, being aspects of luck, they may also be beyond your control and influence. Tend those things you can control with care, and learn not to agonize over the ones you cannot.", "The actions of your past are the seeds of your future success. To make progress, you must accept the changes coming.", "There is a beneficial change approaching, but keep in mind that luck is out of your control.", "The future will yield an opportunity to change paths towards personal growth and happiness. You must be ready to change your ways of thinking, because whether or not your actions bring success, they represent beneficial change.", "https://www.trustedtarot.com/img/cards/wheel-of-fortune.png");
		Cards justice = new Cards("Justice", "Justice is a very good card to find in your spread if you have acted with kindness and fairness towards other and, especially, if you have been a victim. It is a significant indicator of a positive resolution, although how and what sort will depend on your own experiences. If you have been unfair, abusive, or otherwise shady and immoral in your dealings, though, pay heed. For the unjust, this card is, at best, a dire warning to change your ways before retribution falls upon you, and, at worst, a simple statement that it is already too late. In neutral cases, it may simply be telling you to seek out balance in your life.", "Balancing your emotions will pay off and bring you harmony in relationships. The confusion of your life can be overcome if you find inner balance.", "You wil receive some gift of advice or have a debt repaid to you.", "When all is said and done, you will receive the outcome that you truly deserve. Your moral character will be justified, so maintain integrety and strive to balance yourself.", "https://www.trustedtarot.com/img/cards/justice.png");
		Cards hanged = new Cards("The Hanged Man", "The Hanged Man can be interpreted in two very different ways. All change is a small kind of death, as the old must die to create the new, and it may simply indicate upheaval or change in your future, perhaps beyond your control, but more likely a decision that, for good or ill, you will not be able to turn back from. The other interpretation is one of sacrifice, although whether this sacrifice is small or great may not be easily interpreted. Both interpretations imply permanence, and that you should give very careful thought to the decisions in your life.", "Letting go of some things from your past has brought new value to your spiritual life. That which you sacrificed must be seen in a new way.", "If there is something being rushed, this may suggest that it is going to pause. Keep in mind that the act of giving help is not more important than the person being helped.", "Many things are unknown to you now, so you must make new goals and plan carefully. Acting at the right moment will get you ahead.", "https://www.trustedtarot.com/img/cards/the-hanged-man.png");
		Cards death = new Cards("Death", "Death is indicative of change in your future. This change can be in almost any aspect of your life, but it will almost certainly be permanent, significant, and absolute. Death suggests a complete severance between the past and the future, and it will likely be painful. Despite the sense of loss that may accompany it, Death fills an important and natural role in life, and leads eventually to acceptance. It is a necessary part of moving forward, and you will find the changes easiest if you embrace them, rather than fight them. Expect the end of a close friendship, a job, a marriage, or even a life, but do not focus too greatly on the negative.", "You have moved into a new phase of life. All things change with time, and your path through this world is no different.", "A major event is approaching and will arrive suddenly. You will lose something valuable.", "To move forward, develop a new perspective on the world. The past is behind you and the rest of your life is still ahead of you, so continue the journey with all your heart.", "https://www.trustedtarot.com/img/cards/death.png");
		Cards temperance = new Cards("Temperance", "An optimistic card, Temperance encourages you to find balance in your life and approach problems with a calm demeanour. It recognizes that opposing forces need not be at war within you. Tread carefully in any major decisions you make, with confidence that good decisions will lead to a good resolution for you.", "The experiences you've had learning to work in harmony with others will be an ongoing trend. Balancing the material and psychic elements in your life has deeply influenced you.", "Something you have long desired will come to fruition. Expect a wealthy partnership or marriage to develop in your immediate social circle.", "Take control of your life and practice moderation. By staying in balance, you will resolve any current conflicts and begin a new chapter in your life.", "https://www.trustedtarot.com/img/cards/temperance.png");
		Cards devil = new Cards("The Devil", "The Devil is in the business of entrapment. It signifies a situation from which there is no escape, or a road leading to one. Forewarning may let you avoid the trap, or it may not. What sort of trap, and how you might avoid it, depends on where the Devil appears in your spread, and what other cards surround it. This card does not foretell doom, only the need for prudence.", "One of the choices you've made was wrong for you. Negative forces are slowing your development.", "There is an event beyond your influence that will change your life. It is uncertain whether it is good or bad, but avoid extravagant behavior and be true to yourself.", "The time is coming that you will have to find beauty within yourself and stop the projections you are casting on the world. Find the courage to change your life. The course of your life is beyond your knowing, but this awareness will defeat your self-delusions.", "https://www.trustedtarot.com/img/cards/the-devil.png");
		Cards tower = new Cards("The Tower", "Dark and foreboding, the Tower is the embodiment of disruption and conflict. Not just change, but the abrupt and jarring movement caused by the unforeseen and traumatic events which are part of life. The Tower in your spread is always a threat, but life inevitably involves tragedy, and you must decide whether you will face it with grace.", "To make room for the new, the old must be destroyed. The ambitions that you have been following are built on weak foundations and offer false rewards.", "A conflict is coming to a head in your life. Relationships will need to be reevaluated and restructured in order to maintain.", "By withstanding the coming challenges, your future will be bright. Seein things as you want them to be in order to make them become that way. Knowing the worst is behind you can give strength.", "https://www.trustedtarot.com/img/cards/the-tower.png");
		Cards star = new Cards("The Star", "The Star's presence signifies a period of respite and renewal for you. This renewal may be spiritual, physical, or both. It is a particularly positive sign if you or someone close is recovering from illness or injury. It is a light in the darkness, illuminating your future and your past.", "Move on from the hardships of the past and begin your renewal. At the end of all struggles will be peace; rely on your inner strength and external support systems.", "Consider balance and restraint when finding solutions to your current problems. The right amount of help and encouragement will bring harmony and happiness to your circles.", "The time of your renewal is approaching. You have chosen the right path to restore your mental and physical health. By being brave enough to choose the riskier roads, you will inspire those around you.", "https://www.trustedtarot.com/img/cards/the-star.png");
		Cards moon = new Cards("The Moon", "Something in your life is not what it seems. Perhaps a misunderstanding on your part, or a truth you cannot admit to yourself. It may also indicate something important being kept from you by another. This may be a source of worry or depression in your life, and the Moon is a strong indicator that you must rely on your intuition to see through the subterfuge.", "Your understanding of a past event may be distorted by your current perceptions. Reflect on your history and make sure the pieces fit together. By eliminating uncertainty, you will find more peace.", "There is a challenge approaching, taking the form of either a new creative project or a conflict in a relationship. Your history will reveal the best course of action.", "Your imagination will bring you success if your thoughts are coupled with practical action. The struggle to reach your potential may bring about many conflicts in your life, but the results will be beautiful.", "https://www.trustedtarot.com/img/cards/the-moon.png");
		Cards sun = new Cards("The Sun", "As an inherently good influence, finding the Sun is a positive development. It is suggestive of personal gain, and that personal goals and joy are within reach, if you are willing to invest the effort to actualize them. If you are embarking on a new personal venture, such as marriage or beginning a family, the Sun is of particular influence.", "The successes you have achieved in the past will set the stage for future joys. Continue developing your line of work or field of study and the rewards will come.", "There is an opportunity for new friendship or a relationship that will lead to happiness and contentment. Do not give up and you will be led to success.", "You are approaching a moment that has the potential to change your life. Take full advantage of this time and you will achieve a future of endless possibility.", "https://www.trustedtarot.com/img/cards/the-sun.png");
		Cards judgement = new Cards("Judgement", "Judgment tells a story of transition, but unlike Death or the Tower, it is not sudden change, or born of luck or intuition, but change that springs from reason. It signifies plans, often long in the making, coming to fruition. If it points towards the future, it may also speak towards the nature of the change; if there is a choice that needs to be made, ruminate and let your mind guide the decision. Logic, in this case, is a better guide than intuition. Be prepared to make a major decision in your life, likely one that will shape the next chapter of your life.", "Your past is full of good work, but the process of your liberation from those experiences is ongoing. You are beginning a new chapter in your life.", "The present has arrived and the past is relinquishing its hold on your fate. This is the best time to change an element of your lifestyle.", "The fruits of your decisions are coming and you will receive that which you deserve. The path at your feet and the direction it is leading you are clear. You will see your ultimate desire through to the end.", "https://www.trustedtarot.com/img/cards/judgement.png");
		Cards world = new Cards("The World", "The World is an indicator of a major and inexorable change, of tectonic breadth. This change represents a chance for you to bring about a desirable end to the Old and a good beginning to the New. It is indicative of growing maturity, a sense of inner balance and deeper understanding. It suggests that you may be approaching a more final sense of identity, and the security in the self that comes with age. It also represents the falling away of boundaries, sometimes in the effusive sense of the spiritual, but sometimes in a purely physical sense, indicating travels or journeys in the future.", "The path you are on will eventually bring you full circle. It may take a while to realize this, but the journey will allow you to accept new responsibilities and points of view.", "The present moment will bring you the fulfillment of a wish or a long desired change in scenery. To find satisfaction, you must accept the ideas of others to be equally valid as your own.", "You must find your purpose to accomplish it. The same with dreams; you must first be aware of it to make it exist. There is no guarantee for success but the experience you gain will have the potential to fulfill your desires.", "https://www.trustedtarot.com/img/cards/the-world.png");

		deck.add(fool);
		deck.add(magician);
		deck.add(priestess);
		deck.add(empress);
		deck.add(emperor);
		deck.add(hierophant);
		deck.add(lovers);
		deck.add(chariot);
		deck.add(strength);
		deck.add(hermit);
		deck.add(wheel);
		deck.add(justice);
		deck.add(hanged);
		deck.add(death);
		deck.add(temperance);
		deck.add(devil);
		deck.add(tower);
		deck.add(star);
		deck.add(moon);
		deck.add(sun);
		deck.add(judgement);
		deck.add(world);
	}
	
	/**
	 * returns the contents of the deck of cards
	 * @return the list of cards
	 */
	
	public static ArrayList<Cards> getDeck() {
		AddCardDeck();
		return deck;
	}
	
	/**
	 * 
	 * @param name
	 * @param description
	 * @param past
	 * @param present
	 * @param futur
	 * @param image
	 * @return a message indicating that the card has been successfully saved
	 */
	
	public String addCard(String name, String description, String past, String present, String futur, String image) {
		
		deck.add(new Cards(name, description, past, present, futur, image));
		return "The card has been registered!";		
	}


}
